version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://13.203.154.186:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_QUORUM_VOTERS: 1@13.203.154.186:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@13.203.154.186:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    networks:
      - kafka_network
    volumes:
      - kafka-data:/var/lib/kafka/data

  app:
    build: .
    container_name: selenium-kafka-app
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER: "13.203.154.186:9092"
    depends_on:
      - kafka
    networks:
      - kafka_network

volumes:
  kafka-data:

networks:
  kafka_network:
    driver: bridge
